### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by H4xl0r**
+ Landing Page Browser Stats 
on Dashboard

### CODE REVIEW

**Comment by frozenjava** [comment]
@H4xl0r I like it! Can you also add the same feature for targeted portals? You can just copy and paste the code to this file here:

https://github.com/frozenjava/EvilPortalNano/blob/master/EvilPortal/includes/targeted_skeleton/default.php

Also, where/how do you plan on displaying this data?

**Comment by H4xl0r** [comment]
Works out of the box mate :-) 
its the old ancient landing page function from Pinapple itself 
its already implemented into the pine 
just add it to the portal 
and it will show up in the dash under Landing Page Browser Stats (normaly empty)

**Comment by frozenjava** [comment]
Ah I see. Well go ahead and add it to the targeted portal page and I'll go ahead and merge it

**Comment by H4xl0r** [comment]
will pull with full update

**Pull request closed without merging**
