### PR TITLE
Development

### PR DESCRIPTION
**Pull request by TheTr1ckster**

### CODE REVIEW

**Comment by frozenjava** [comment]
Im not ready to merge this yet. I've started a refactor for 3.0 - keep an eye on the nightly branch.

**Comment by TheTr1ckster** [comment]
Okay, cool!  When’s 3.0 coming?!

 

 

Senior Consultant | CounterHack Ltd.

 

E : Richard@CounterHack.co.uk

M : 07974423446

W : www.counterhack.co.uk

**Comment by frozenjava** [comment]
The goal is to have it ready for Hack Miami which is this weekend (May 19th). With that said, it just so happens that my schedule got filled up this week so it might be a bit of a stretch to make that goal happen.

**Comment by TheTr1ckster** [comment]
I hear ya! Had an ‘interesting’ weekend too….    ;^)

 

 

Senior Consultant | CounterHack Ltd.

 

E : Richard@CounterHack.co.uk

M : 07974423446

W : www.counterhack.co.uk

**Pull request closed without merging**
