### PR TITLE
Update index.php and https blocking

### PR DESCRIPTION
**Pull request by H4xl0r**
Fixed Request to be able to intercept http and https .

### CODE REVIEW

**Comment by frozenjava** [comment]
This looks like it will work. I'll test it this week and merge if it does. Good work

**Comment by H4xl0r** [comment]
Still need to fix the redirect function itself , its not working .
see #24

**Comment by frozenjava** [comment]
Looks like you have a bug fix and a feature in this one PR. Would you mind splitting them up into two different PRs?

**Comment by H4xl0r** [comment]
sure will delete repo and then pull again 
the other one i will then push later

**Pull request closed without merging**
