### PR TITLE
Https Http Fix 

### PR DESCRIPTION
**Pull request by H4xl0r**

### CODE REVIEW

**Comment by H4xl0r** [comment]
Should be the same pull ....

**Comment by frozenjava** [comment]
Just tested. Everything works so merging this.

**Comment by kleo** [comment]
Just to clarify, current changes drop/~~redirect~~ https connections. Disallowing clients to connect to the internet using https connection. 

This does not actually spoof the original url i.e https://example.com to the Evil Portal.

Tested on mobile browsers, on Chrome ERR_SSL_PROTOCOL_ERROR and on Firefox SSL_ERROR_RX_RECORD_TOO_LONG.

**Comment by H4xl0r** [comment]
there is no other way around , the only solution for this is the redirect function i think, https block works with iptables , not possible to redirect client specific original urls ....

but with the destination info in your form it should work (eg google login )
but i understand your point !

**Pull request merged**
